### PR TITLE
Add pyproject.toml support + rewrite pre-commit hooks + lint

### PR DESCRIPTION
**Pull request by oscarmcm**

### CODE REVIEW

**Comment by oscarmcm** [comment]
@benjaoming please feel free to check this.

**Comment by benjaoming** [comment]
@oscarmcm sounds good! Is there any more work you've planned here?

**Comment by oscarmcm** [comment]
@benjaoming I think nothing else here is pending to be completed or added.

**Review by benjaoming — APPROVED** [review]
Fantastic work :star_struck:

**Pull request merged**
