### PR TITLE
Isort configuration

### PR DESCRIPTION
**Pull request by rsalmaso**
Added isort config and run with these rules.

### CODE REVIEW

**Comment by rsalmaso** [comment]
@benjaoming I'm not really sure about it but it use the same conventions in `django-wiki`

**Comment by benjaoming** [comment]
@rsalmaso seems cool, thanks - is this still WIP?

It would need some kind of linting in Travis to maintain it over time, though.

**Comment by rsalmaso** [comment]
No, it should be ok now.

**Comment by benjaoming** [comment]
Thanks! :)

**Pull request merged**
