### PR TITLE
Support django-channels 2 - this PR is looking for someone to take over and finish the work

### PR DESCRIPTION
**Pull request by yevheniidehtiar**
I want to share upgraded version that work with channels 2.
Sorry, It's my first pull request and I am easy in license and, can u help me with it. Maybe append it reuqest as new branch.

### CODE REVIEW

**Comment by benjaoming** [comment]
Hi friend! Thanks for the PR! I'm not going to be able to review it, though, because the diff is a bit of a mess :)

It seems you are PR'ing against the `releases/1.0.x` which is a stable release branch, i.e. new features wouldn't go into this branch, anyways. Could you perhaps have a look at the `master` branch where new development should take place?

Thanks :)

**Comment by benjaoming** [comment]
Okay, I've changed the base branch, that seems to work -- @yevheniidehtiar could you confirm if the diff looks as intended?

**Comment by yevheniidehtiar** [comment]
Hi, yes the diff looks right 👍 Thank you man)

**Comment by benjaoming** [comment]
@yevheniidehtiar would you be able to resolve the conflicts, and then we can check if tests are running?

**Comment by benjaoming** [comment]
@yevheniidehtiar A lot of great work here, looking forward to seeing it merged :) Could you start by merging the current master of this repository into your branch? This will lead to some merge conflicts that I don't think look very complicated.

I'm a bit hesitant to make changes in your branch since it's your `master` branch and I assume you might be using it for something?

**Comment by yevheniidehtiar** [comment]
Ok, man. When I will have free time fo this. I merge and create new pull request with my new updates, like messaging over websocket between two clients and bug-fixes with async methods.

**Comment by benjaoming** [comment]
> Thank you man
> Ok, man

Since today is indeed the International Men's Day, I thought to just quick ask and encourage that your work on this isn't forgotten - but that you are most welcome to resolve the conflicts and we'll get this in! :pray:

**Comment by yevheniidehtiar** [comment]
Hi guys, seems i forgot it couple years ago and gonna to finish it soon)

**Comment by benjaoming** [comment]
That sounds great, am hear to help resolve decisions and get things merged, much appreciated to have this PR finished :+1:

**Comment by benjaoming** [comment]
Hi @yevheniidehtiar :wave: 

Time flies :)

A lot of work went into this, I was wondering if you could share some background on this PR? Do you have a project that's already running this code? And if so, does it work well?

**Comment by yevheniidehtiar** [comment]
> Hi @yevheniidehtiar 👋
> 
> Time flies :)
> 
> A lot of work went into this, I was wondering if you could share some background on this PR? Do you have a project that's already running this code? And if so, does it work well?

Hi @benjaoming 

Yeap, time flies! Children grows :)

Django is already version 3 and soon 4.
I had a project in 2019 where this code was working very well.

Have no visible space in the agenda. It might be that it's gonna be updated again when I got a reason to use it.

**Comment by yevheniidehtiar** [comment]
Closed as you already updated to channels 4 :)

**Pull request closed without merging**
