### PR TITLE
Update MANIFEST.in

### PR DESCRIPTION
**Pull request by rsalmaso**
The generate whl lacks locale and template files

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks - I get why it would be missing. But I don't understand how Tox tests manage to complete. Are they not using any of these files? :/

From Tox documentation:

> (...) To **sdist-package**, install and test your project, you can now type at the command prompt:

http://tox.readthedocs.io/en/latest/example/basic.html

As I understand it, Tox would build the dist (which should fail to include these files), and then run the tests after. Our tox.ini doesn't specify `usedevelop`.

**Comment by rsalmaso** [comment]
Oh, I'm used to `python setup.py bdist_wheel`, never used tox so can't explain.

**Comment by benjaoming** [comment]
Thanks for finding this issue -- it was working because there was also a `MANIFEST` file AFAIK which should be auto-generated by setuptools from `MANIFEST.in` and not in the git repo. Fixed it up in #72

**Comment by rsalmaso** [comment]
:smile_cat:

**Pull request closed without merging**
